name: Update README

on:
  schedule:
    - cron: '0 */12 * * *'  # Runs every 12 hours
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Stats
        uses: anmol098/waka-readme-stats@master
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
